### ISSUE TITLE
got error: Unable to resolve host "cp.cloudflare.com" No address associated with hostname

### ISSUE THREAD

**Issue by yyyy777** [hamid-nazari/ShadowsocksGostPlugin#1]
![2e766786fc038f3524656acfb4ebe7df](https://github.com/hamid-nazari/ShadowsocksGostPlugin/assets/11991089/2d743584-5f4d-4056-9b9b-ee363512e067)
when i tried connect, i got this error, how to fix it?

**Comment by yyyy777** [comment]
on my mac and windows, this gost config is ok

**Comment by hamid-nazari** [comment]
I've seen this when upgrading from profiles working with older plugin releases, and mainly there was no issue with the tunnel setup, but this error is shown anyway.
I suggest creating a fresh profile in Shadowsocks after installing this plugin and transfer your settings to it.
Also, it would be helpful if you could export and attach your Shadowsocks profile for my inspection.
Please copy your profile and remove any sensitive data before exporting it.

**Comment by yyyy777** [comment]
> I've seen this when upgrading from profiles working with older plugin releases, and mainly there was no issue with the tunnel setup, but this error is shown anyway. I suggest creating a fresh profile in Shadowsocks after installing this plugin and transfer your settings to it. Also, it would be helpful if you could export and attach your Shadowsocks profile for my inspection. Please copy your profile and remove any sensitive data before exporting it.

i created a new profile, still not worked. 

![image](https://github.com/hamid-nazari/ShadowsocksGostPlugin/assets/11991089/79433539-4089-43cd-bf26-c7e0aa310e20)

this is my profile.
and my shadowsocks version is 5.3.3

**Comment by hamid-nazari** [comment]
To be able to reproduce this issue, I setup a HTTP+TLS service on my server and used this encoded config to setup a profile in Shadowsocks and had no issue connecting a tunnel (of course I added authentication details).

I think you are missing a few config ingredients here. For instance, a TLS setup requires a form of key exchange, therefore you normally would provide your own private key (since there is no auth info in your profile), or to be more safe, specify the expected server's certificate. I don't see them here.

Note also that there is a slight difference between how Shadowsocks works and how you would use GOST directly on Mac or Windows.

If the server is under your control, I suggest debugging the issue by adding a more trivial setup like using RELAY or HTTP service on another port for this Android client. I might be able to assist you with the YAML config of the server.
Otherwise, I would need more context to be able to help you out here. For example, your working Windows GOST client config is needed so that I can reproduce your exact setup.

**Comment by yyyy777** [comment]
i use .\gost.exe -L ss://aes-128-gcm:passcode@:20084 -F '{myserver}:{myport}' on my windows and mac, then my shadowsockt connect 127.0.0.1:20084 with password passcode.

**Comment by yyyy777** [comment]
> 为了能够重现这个问题，我在我的服务器上设置了一个 HTTP+TLS 服务，并使用这个编码的配置在 Shadowsocks 中设置了一个配置文件，连接隧道没有问题（当然我添加了身份验证详细信息）。
> 
> 我认为您在这里缺少一些配置成分。例如，TLS 设置需要一种密钥交换形式，因此您通常会提供自己的私钥（因为您的配置文件中没有身份验证信息），或者为了更安全，请指定预期的服务器证书。我在这里没有看到它们。
> 
> 另请注意，Shadowsocks 的工作方式与您直接在 Mac 或 Windows 上使用 GOST 的方式略有不同。
> 
> 如果服务器在您的控制之下，我建议通过添加更琐碎的设置来调试问题，例如在此 Android 客户端的另一个端口上使用 RELAY 或 HTTP 服务。我也许可以帮助您完成服务器的 YAML 配置。否则，我需要更多的上下文才能在这里为您提供帮助。例如，需要您工作的 Windows GOST 客户端配置，以便我可以重现您的确切设置。

I use .\gost.exe -L ss://aes-128-gcm:passcode@:20084 -F '{myserver}:{myport}' on my windows and mac, then my shadowsockt connect 127.0.0.1:20084 with password passcode.

while i noticed the android gost plugin, -L config is ss://none, so i didn't set the shadowsocks password.

maybe the dns.google is wrong? Do you think that's one of the possibilities?

**Comment by hamid-nazari** [comment]
> I use .\gost.exe -L ss://aes-128-gcm:passcode@:20084 -F '{myserver}:{myport}' on my windows and mac, then my shadowsockt connect 127.0.0.1:20084 with password passcode.

Do you use HTTPS for '{myserver}:{myport}'?
 
> while i noticed the android gost plugin, -L config is ss://none, so i didn't set the shadowsocks password.

Well, this is a correct assumption.

> maybe the dns.google is wrong? Do you think that's one of the possibilities?

Maybe. Try setting any accessible DNS server. Note that GOST does not use value set in Shadowsock profile, rather it uses its own DNS server settings (at the bottom of the config page of the plugin) and is now set to 8.8.8.8:53. I'd suggest you change that to 119.29.29.29:53, like the previous default value.

**Comment by yyyy777** [comment]
> > I use .\gost.exe -L ss://aes-128-gcm:passcode@:20084 -F '{myserver}:{myport}' on my windows and mac, then my shadowsockt connect 127.0.0.1:20084 with password passcode.
> 
> Do you use HTTPS for '{myserver}:{myport}'?
> 
> > while i noticed the android gost plugin, -L config is ss://none, so i didn't set the shadowsocks password.
> 
> Well, this is a correct assumption.
> 
> > maybe the dns.google is wrong? Do you think that's one of the possibilities?
> 
> Maybe. Try setting any accessible DNS server. Note that GOST does not use value set in Shadowsock profile, rather it uses its own DNS server settings (at the bottom of the config page of the plugin) and is now set to 8.8.8.8:53. I'd suggest you change that to 119.29.29.29:53, like the previous default value.

wow, 119.29.29.29:53 is worked!!!!!  thank you so much, you are very patient!!

**Comment by hamid-nazari** [comment]
Glad to be of assistance, and I learnt from this too

**Comment by cnscorpions** [comment]
> > > I use .\gost.exe -L ss://aes-128-gcm:passcode@:20084 -F '{myserver}:{myport}' on my windows and mac, then my shadowsockt connect 127.0.0.1:20084 with password passcode.
> > 
> > 
> > Do you use HTTPS for '{myserver}:{myport}'?
> > > while i noticed the android gost plugin, -L config is ss://none, so i didn't set the shadowsocks password.
> > 
> > 
> > Well, this is a correct assumption.
> > > maybe the dns.google is wrong? Do you think that's one of the possibilities?
> > 
> > 
> > Maybe. Try setting any accessible DNS server. Note that GOST does not use value set in Shadowsock profile, rather it uses its own DNS server settings (at the bottom of the config page of the plugin) and is now set to 8.8.8.8:53. I'd suggest you change that to 119.29.29.29:53, like the previous default value.
> 
> wow, 119.29.29.29:53 is worked!!!!! thank you so much, you are very patient!!

没看到这个dns配置项？
Seems there is no config option for it?
