### ISSUE TITLE
Can I choose not to use the 'dns server' option in the plugin?

### ISSUE THREAD

**Issue by yqk100** [hamid-nazari/ShadowsocksGostPlugin#2]
Reason:
The plugin 'dns server' can cause DNS leaks and is not as flexible as Gost's own DNS related parameters.

So I don't want to use the plugin option 'dns server' and instead use Gost parameters for usage.

**Comment by hamid-nazari** [comment]
This part of the upstream code had me wondering, too.
Since I targeted this release for a revival and update of dependencies, I changed as little as possible.
This part is what I did not touch.
 
I'll go over it for the next release and will post updates here when I have a more definitive answer.
Thanks for raising this concern.

**Comment by zoghal** [comment]
عرض سلام و تشکر مخصوصا از بابت این دست گرفتن این پروژه و زنده کردن دوباره اون.👏
اگر بتوانید این روح بی روح رو مستقلش کنی از این اپ شادوساکس یا پلاگینش کنی به v2ray واقعا عالی میشه.🫡

**Comment by Typhonling** [comment]
As I understand it, the DNS server in the ShadowsocksGostPlugin is only used to resolve ${remote.host}, other links via VPN use the Remote DNS settings in Shadowsocks.

**Comment by hamid-nazari** [comment]
I have not gone through this thoroughly as I just aimed to revive the code and make it compatible with the latest GOST version. But, what I can see from the code is that I need to patch GO runtime (used to invoke GOST), by injecting the provided DNS server. So, I suspect it would intercept all name resolutions, but have not yet tested is though,

**Comment by Typhonling** [comment]
https://gost.run/en/concepts/resolver/

> The resolver in the service resolves the target address of the request, and the resolver in the forwarding chain resolves the node addresses.

So you need to confirm whether the resovler in this project is applied to the server or the chain.

**Comment by hamid-nazari** [comment]
As I've mentioned [earlier](https://github.com/hamid-nazari/ShadowsocksGostPlugin/issues/2#issuecomment-2308460461) I'm pretty much sure that the *DNS Server* setting is applied to **GO runtime** and hence all DNS resolution goes through that server, no matter where in GOST config they appear.
I've planned to remove this and allow full GOST compliance for the next release.

**Comment by hamid-nazari** [comment]
This issue is now addressed in release v4.1.0
