### ISSUE TITLE
这个插件配置quic协议连不上服务器

### ISSUE THREAD

**Issue by WSitong** [hamid-nazari/ShadowsocksGostPlugin#3]
这个插件要怎样使用，有相关文档吗？我尝试了很多配置方法都会连接失败，也看不到错误信息。我的目的是用quic作为传输协议，我应该以怎样的参数启动服务端，以及我要怎样配置客户端？有谁知道吗？

**Comment by WSitong** [comment]
我已经找到原因了，原来是配置后面还跟了一些参数，因为输入框长度不够，我没有看到。去掉多余的参数就好了

**Comment by hamid-nazari** [comment]
I'm glad you've managed to find the issue and resolve it.
As you pointed out about the lack of log and is totally correct, I recommend coming up with a working GOST configuration using the command line on Linux or Windows and then transfer the config onto this plugin to work with SS
