### ISSUE TITLE
Everything is fine, just how should gost.yaml be used?

### ISSUE THREAD

**Issue by Typhonling** [hamid-nazari/ShadowsocksGostPlugin#4]
Compared to 2.11, 4.0 solves the problem of breaking at “&” in commands.
Compared to 3.0.0RC, 4.0 solves the problem that Server can only use domain name but not IP.
What should I do if I want to use gost.yaml? I followed the example and tried just filling the chains field and it doesn't seem to work.

**Comment by hamid-nazari** [comment]
As I've mentioned in plugin's configuration help, in contrast to previous versions, the GOST config file which is named `config.yaml` is always included on GOST's command line; that is, a `-C config.yaml` is always passed on to GOST. I make sure this file is always created properly before GOST is invoked and have the right contents equal to what user enters in the text box. All issues with relative paths and data folder are handled correctly in this version.
The only thing that users must pay attention to when specifying GOST config through this file is the fact that specifying any chain configuration in `config.yaml` overrides those passed through the command line and this is GOST's behavior. So all `-F`'s and `-L`'s would become stale and irrelevant when chain is configured through the config file. 
Therefore, users must always include the equivalent service setup for the `ShadowSocks Android` on `localhost` to connect equivalent to the first `-L ss://none@${local.host}:${local.port}` option I add by default.

Hope this would help you.

**Comment by Typhonling** [comment]
As you mentioned,  `-L ss://none@${local.host}:${local.port}` should also be invalid, so I should fill it in like in the picture below:

![Image](https://github.com/user-attachments/assets/ce98e10c-ac3b-4d43-84fa-a9ad1443b5c2)

So my question is, in config.yaml, how should I define `${local.host}` and `${local.port}`?

```
services:
- name: service-0
  addr: ${local.host}:${local.port}
  handler:
    type: ss
    auth:
      username: none
    chain: chain-0
  listener:
    type: tcp
chains:
```

**Comment by hamid-nazari** [comment]
The `config.yaml` is always included, whether you specify `-C` flag like the image you attached or not.
But the issue is with the `${local.host}` and `${local.port}` and other variables that are not replaced in passed-in config files.
I'll try to release a new version today, but unfortunately, the config file you've attached won't work with the current release.

**Comment by hamid-nazari** [comment]
I cooked a new release to address this issue [v4.2.1](https://github.com/hamid-nazari/ShadowsocksGostPlugin/releases/tag/v4.2.1).
Now you can use your sample `config.yaml`, provided it is a correct GOST configuration.

**Comment by Typhonling** [comment]
Wow, that's super efficient. Thank you for your work.

However, according to my tests, the `-C config.yaml` must be filled in. if this field is left blank or left at the default `-L ss://none@${local.host}:${local.port}`, it does not work. 

Other than that, everything worked as expected. The example diagram is as follows:

![Image](https://github.com/user-attachments/assets/f88bb1ba-e786-4e41-a1a8-bb0228474132)

**Comment by Typhonling** [comment]
Additionally, I would suggest that you try [Exclave](https://github.com/dyhkwong/Exclave), which is a more modern v2ray-core based client, compatible with the SIP003 plugin for Shadowsocks, with better control over traffic, and addresses DNS leaks caused by certain settings in Shadowsocks Android.
